spring.application.name=api-gateway
server.port=8080

security.jwt.secret=change-this-to-a-long-random-256-bit-secret-key

services.submissions.url=http://localhost:8082
services.payments.url=http://localhost:8083

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
