spring.application.name=api-gateway
server.port=8080

security.jwt.secret=${SECURITY_JWT_SECRET:change-this-to-a-long-random-256-bit-secret-key}

services.submissions.url=${SERVICES_SUBMISSIONS_URL:http://localhost:8082}
services.payments.url=${SERVICES_PAYMENTS_URL:http://localhost:8083}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
